0:
  theta: -1.6397860376118132
  x: -1.0459399768326416
  y: -0.2696363444420663
1:
  theta: 0.010179669780128643
  x: 0.9148117353678101
  y: -1.2542870582462553
2:
  theta: -0.0027348365991071094
  x: 2.6611632183604277
  y: -1.7026228423030687
3:
  theta: 1.5578704686646063
  x: 4.1737701754325425
  y: -1.4142412501237631
4:
  theta: 1.5648444171364047
  x: 3.642911203868881
  y: 1.0761312012171484
5:
  theta: 1.5677446359566374
  x: 3.512475450166431
  y: 2.713132371137554
6:
  theta: 3.122838528872511
  x: 3.096040234856562
  y: 4.666989475640261
7:
  theta: 3.129414018189954
  x: 1.6649970925516582
  y: 3.969136565736828
8:
  theta: -1.5869158579702947
  x: -1.0503666073318132
  y: 4.16295046395833
